data:
  upload_folder: "shared_data/uploads/"
  archive_folder: 'shared_data/archive/'  
  input_template_folder: 'shared_data/input_templates/'
  download_template_folder: 'shared_data/output_templates/'

storage:
  chroma_host: "chromadb"
  chroma_port: 8000  
  collection_name: "dhf_chunks"  
  chunk_size: 300
  chunk_overlap: 50

embedding:
  embed_model: "mxbai-embed-large"
  ollama_url: "http://ollama:11434"

llm:
  fm_model: "llama3"
  max_results: 5
  temperature: 0.4
  max_tokens: 2048

openai:
  api_key: "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"
  model: "gpt-4o"
  base_url: "https://api.openai.com/v1"

langsmith:
  enable_tracing: true
  endpoint: "https://api.smith.langchain.com"
  api_key: "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"
  project: "default"
  
logging:
  log_level: "INFO"

environment:
  - MODEL_NAME="papluca/xlm-roberta-base-language-detection"
  - HF_TOKEN="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"